# Spawn location to teleport players to
# Set this to 'null' to disable
spawn: 'null'

# Height below which players are considered to be in the void
# You might want to change this when running a server in 1.18 or later
# Also useful if your lobby is built very high, to reduce the falling distance
void_height: 0
