name: VoidTeleport
version: 1.0.0
author: DarthChungo
description: Minecraft Spigot plugin for preventing players from falling into the void

main: me.DarthChungo.VoidTeleport.VoidTeleport
api-version: '1.13'

commands:
  voidteleport:
    description: set and test the void teleport location
    aliases:
      - vtp

permissions: {}
